print("HELLO WORLD!\n YEEEEEEEEEHAW")
print("python is interesting")
print("yeet")
print("daily thought \n everything is pain")
print("daily thought \n everything is pain")
print("merry chrimbus eve!")
print("day 1")
print("day 1")
print("2 days til cs25")
print("CS DAY 2")
print("2 days til cs25")
print("CS DAY 2")
